USE [master]
GO

/****** Object:  Database [EM]    Script Date: 20-04-2017 17:21:45 ******/
CREATE DATABASE [EM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\EM.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\EM_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EM] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EM] SET ARITHABORT OFF 
GO

ALTER DATABASE [EM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EM] SET  MULTI_USER 
GO

ALTER DATABASE [EM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EM] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EM] SET  READ_WRITE 
GO

